import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from '../components/Navbar';
import TopHeader from "@/components/TopNavbar";
import Footer from "@/components/Footer";
import { CartProvider } from "../app/context/CartContext";
import { WishlistProvider } from "../app/context/wishContext";
import { Roboto } from "next/font/google";
import Navbar1 from "@/components/Navbar1";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const roboto = Roboto({
  weight: "400", // Specify weights like 400, 700, etc.
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
           className={`${roboto.className} font-sans`} 
      >
         <CartProvider>
         <WishlistProvider>
        <TopHeader/>
        <Navbar1/>
        <main>
        {children}
        </main>
        <Footer/>
        </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
